version: 2

sources:
  - name: nyc_311                       # Logical source name
    database: bigquery-public-data  # Optional in BigQuery, usually same as project
    schema: nyc_311                     # BigQuery dataset name
    freshness:                      # Dataset freshness: Optional
      warn_after: { count: 32, period: day }
      error_after: { count: 40, period: day }
    tables:
      - name: 311_service_requests                # Table name in BigQuery
        description: "NYC 311 service requests data"
        columns:
          - name: unique_key
            description: "Unique identifier for each 311 service request"
            tests:
              - not_null


  - name: census_bureau     # Logical source name
    database: census_bureau_acs    # Optional in BigQuery, usually same as project
    schema: zip_codes_2018_5yr   # BigQuery dataset name
    tables:
      - name: zip_codes_2018_5yr                # Table name in BigQuery
        description: "ZIP code data from the 2018 5-year ACS."
        columns:
          - name: zip_code
            description: "ZIP code"
            tests:
              - not_null
              - unique
